### ISSUE TITLE
Logo offer for Wifiauto

### ISSUE THREAD

**Issue by familqasimov** [alexandreroman/wifiauto#1]
Hi sir. I would like to offer logo. If you like I can give you all the formats of the design free. If you want a change please specify or select one of them.

![wifiauto](https://user-images.githubusercontent.com/36432269/42121227-45c61730-7c3c-11e8-9233-0ae3d9ae3b84.png)

best regard
Famil Qasimov

**Comment by alexandreroman** [comment]
Thank you very much for this contribution.
I'd like to use logo 1 for the application icon.
Could you please send me this logo in SVG format?

**Comment by alexandreroman** [comment]
Your icon has been integrated.
Thank you for your contribution!
